---

# Returns:
# * aws_vpc_igw_vpc_id
# * aws_vpc_igw_vpc_cidr
- include_tasks: gather_facts.yml

- name: "ensure igw for vpc with id {{ aws_vpc_igw_vpc_id }} is deleted"
  ec2_vpc_igw:
    # Fixed values
    state: absent
    # Looked-up values
    vpc_id: "{{ aws_vpc_igw_vpc_id }}"
    # Optional values
    region: "{{ igw.region | default(aws_vpc_igw_default_region | default(omit)) }}"
    aws_access_key: "{{ lookup('ENV', 'AWS_ACCESS_KEY') | default(omit) }}"
    aws_secret_key: "{{ lookup('ENV', 'AWS_SECRET_KEY') | default(omit) }}"
    security_token: "{{ lookup('ENV', 'AWS_SECURITY_TOKEN') | default(omit) }}"
    profile: "{{ aws_vpc_igw_profile | default(omit) }}"
  when: aws_vpc_igw_vpc_id is defined
